In [1]:
import pandas as pd 
import numpy as np
import csv
import math

In [2]:
user_history = pd.read_csv("user_history.csv")
user_history

,USER ID,alpine kimono,sweden kansas,student icon,supreme ivan,albert charlie,heavy trapeze,fabric tokyo,brother robin,tiger catalog,...,cigar lagoon,equal comedy,bombay podium,helena robot,prodigy rhino,jumbo gray,radius wizard,fame quiz,bazaar complex,glass slogan
0,100950,2.192897,0.361397,0.531663,0.016105,0.694338,1.250662,1.483259,1.799682,0.664616,...,0.309236,2.622033,1.242243,2.947560,0.693319,0.625303,2.352295,1.548417,1.517709,1.508219
1,100956,2.776597,0.788821,1.187149,0.473049,2.245112,1.998881,0.072812,1.441970,2.264368,...,2.304845,1.498307,0.319484,0.089212,3.157167,2.789594,1.003377,1.141516,2.011509,0.377898
2,100962,0.281717,5.046727,4.407484,2.138591,1.075562,0.385842,0.626482,0.026648,1.949374,...,1.463952,0.601814,1.983130,2.364877,0.429133,2.758070,0.563619,0.271453,0.579626,1.785609
3,100969,0.943147,1.165713,2.016138,1.236626,0.973435,2.514205,0.022476,1.091282,1.320748,...,1.428416,3.791742,1.102070,3.250911,1.209403,0.246261,0.558631,1.163652,1.922758,1.008040
4,100974,0.485729,4.633607,4.120416,1.497073,1.463875,0.867737,0.877514,0.019603,1.751483,...,1.179954,1.031741,1.935182,2.012611,0.553173,2.614605,0.313479,0.143246,0.914407,2.011048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,125614,0.200730,3.819307,3.793920,1.352770,1.616516,0.138227,0.193954,0.770098,1.724992,...,0.985254,0.508837,2.033624,2.783638,0.360851,1.787872,0.749357,0.205445,0.945106,1.155107
4496,125622,1.139876,0.361305,1.420300,1.024918,2.313955,1.638803,1.570336,0.233047,1.521743,...,3.606324,1.670899,1.127929,1.888831,4.198021,2.934536,0.501603,0.923039,0.737211,0.675006
4497,125629,2.423679,0.555591,1.244828,0.100391,1.098254,2.027846,1.485342,0.912006,0.304603,...,0.050602,2.439248,1.352124,2.926793,0.254287,0.488679,2.181696,1.367859,1.410247,0.549376
4498,125636,0.096291,3.028528,2.554836,0.404308,1.401119,0.760813,0.356988,1.873021,1.977173,...,0.609813,0.242120,1.061562,2.616126,0.091176,1.162114,1.218459,1.067140,0.441260,0.666655
4499,125645,0.595734,2.072896,1.997112,0.553371,1.674531,0.381437,0.149846,2.993711,1.455024,...,0.825080,0.370440,0.773802,3.314752,0.146642,1.096581,2.257115,1.034738,1.001442,0.267665

In [6]:
user_ratings = pd.read_csv("user_ratings.csv")
user_ratings_table = pd.pivot_table(user_ratings,values='RATING', index='USER ID',
                    columns='PRODUCT')
train_rating = user_ratings_table.sample(frac = 0.8)
test_rating = user_ratings_table.drop(train_rating.index)

In [7]:
train_rating

PRODUCT,adrian crater,anagram mentor,apropos pizza,bandit anatomy,banjo ladder,barcode arnold,bazooka diagram,bronze mystic,calypso zigzag,casino unit,...,tourist micro,tripod stand,update lola,ventura puzzle,viking llama,violet saga,vista queen,viva avalon,voodoo planet,wheel gibson
USER ID,,,,,,,,,,,,,,,,,,,,,
108622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115973,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN
105208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,NaN,3.0,NaN,4.0,NaN,NaN,NaN
115308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102094,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105080,NaN,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101812,NaN,4.0,NaN,8.0,NaN,6.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102797,NaN,NaN,8.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
103689,NaN,NaN,4.0,NaN,NaN,NaN,9.0,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,5.0,NaN,6.0,NaN,NaN,8.0
107486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,7.0,NaN,NaN

In [8]:
test_rating

PRODUCT,adrian crater,anagram mentor,apropos pizza,bandit anatomy,banjo ladder,barcode arnold,bazooka diagram,bronze mystic,calypso zigzag,casino unit,...,tourist micro,tripod stand,update lola,ventura puzzle,viking llama,violet saga,vista queen,viva avalon,voodoo planet,wheel gibson
USER ID,,,,,,,,,,,,,,,,,,,,,
100962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100994,NaN,NaN,9.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
101008,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
101014,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
101067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117375,NaN,5.0,NaN,5.0,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117377,NaN,NaN,NaN,NaN,7.0,NaN,NaN,9.0,NaN,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
117395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117424,NaN,NaN,NaN,NaN,9.0,10.0,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN
117442,6.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN

In [35]:
#Doing PCA (in order to do PCA we must strip the first column then transpose our matrix)
X = user_history.loc[:, user_history.columns != 'USER ID'].to_numpy()
X_meanzero = (X - np.mean(X, axis = 0)) # subtract the mean 
X = (X_meanzero / np.std(X, axis = 0)) # divide by the standard deviation
U,S,Vt = np.linalg.svd(X)
# Compute the fraction of the total spectrum in the first 20 singular values
FractionFromS1_S20 = sum(S[0:20]**2) / sum(S**2)
print("Fraction of Spectrum from sigma's 0 through 20 =", FractionFromS1_S20)

Fraction of Spectrum from sigma's 0 through 20 = 0.9157759743540711

In [39]:
#Now let us use this top 20 singular vectors to make a matrix 
user_data_t20 = pd.DataFrame(data = U[:,0:20], index = user_history['USER ID'])
user_data_t20

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
USER ID,,,,,,,,,,,,,,,,,,,,
100950,-0.004514,0.020640,-0.020294,0.001633,0.022928,0.003242,-0.000566,-0.009533,0.002875,0.011114,-0.003247,0.015920,-0.014082,-0.027663,0.003314,-0.020494,0.007759,-0.019437,-0.017140,-0.009494
100956,-0.013275,-0.014971,0.011113,-0.024348,0.011722,0.006179,-0.041877,0.014490,-0.017272,0.029175,0.001075,0.008859,-0.020262,-0.011826,-0.011004,-0.011540,0.008530,0.005807,-0.006129,-0.003571
100962,0.023204,-0.004410,-0.033476,0.001589,-0.032625,0.015723,-0.012843,0.000361,-0.012203,-0.028207,-0.007989,0.017772,-0.009550,0.023818,0.013880,-0.006188,-0.005444,0.002978,0.000439,-0.020069
100969,-0.001742,0.012079,-0.006056,0.022461,-0.003419,-0.029987,-0.030297,-0.027563,-0.078227,-0.000896,0.027698,-0.028412,0.016049,-0.003456,-0.016262,0.013916,-0.015935,-0.028058,-0.019361,-0.004600
100974,0.020923,-0.005239,-0.035201,0.012253,-0.020897,0.008484,-0.008579,0.014812,0.006463,-0.016204,0.013022,0.034557,0.009984,-0.008302,0.004943,-0.021253,-0.009833,-0.015875,0.031566,0.018078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125614,0.022736,-0.003458,-0.012668,0.003553,-0.007905,0.003855,-0.008565,-0.000553,0.006487,-0.000368,-0.018815,-0.017857,-0.036251,-0.016095,0.018973,-0.019044,-0.011597,0.004553,-0.020916,0.014747
125622,-0.014478,-0.017387,-0.016977,0.003236,-0.010252,-0.021332,0.036730,-0.000793,-0.015585,0.030770,0.010594,-0.020745,-0.014757,0.014419,0.019702,-0.005328,-0.001174,0.008521,0.004882,-0.013083
125629,-0.006893,0.022093,-0.006281,0.000119,0.007419,0.009174,0.007120,-0.000034,0.012132,0.004229,-0.018350,-0.008483,-0.010621,0.013865,0.009743,-0.012128,-0.014544,0.007652,-0.015644,0.002882
125636,0.019059,-0.003738,0.013375,0.007850,0.016433,-0.012886,0.002847,0.010703,0.012990,-0.007089,0.000240,-0.023696,-0.001722,0.008633,-0.024864,-0.004905,-0.001086,0.031716,-0.017576,-0.023300
125645,0.017224,-0.001748,0.029929,-0.013881,0.022258,-0.001620,0.020370,-0.009291,0.005161,0.011625,0.005016,0.005274,0.011874,0.027617,-0.007558,0.027292,-0.003386,-0.020097,0.001612,-0.006570

In [52]:
#Now lets make the matrix that we need to complete: the training values attached to their corresponding user ids
user_data_with_ratings_incomplete = user_data_t20.join(train_rating, how = 'right')
user_data_with_ratings_incomplete

,0,1,2,3,4,5,6,7,8,9,...,tourist micro,tripod stand,update lola,ventura puzzle,viking llama,violet saga,vista queen,viva avalon,voodoo planet,wheel gibson
USER ID,,,,,,,,,,,,,,,,,,,,,
108622,0.016825,-0.002633,0.033250,0.000160,0.029553,-0.011389,0.013860,-0.008588,0.003290,-0.016162,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115973,0.016788,-0.003311,0.026729,0.008950,0.030279,-0.024163,0.011622,0.018237,0.000238,-0.040372,...,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN
105208,-0.013771,-0.016797,-0.001010,0.011856,-0.000322,0.001146,0.007303,-0.007200,0.012348,-0.006214,...,NaN,NaN,4.0,NaN,3.0,NaN,4.0,NaN,NaN,NaN
115308,0.017265,-0.002911,0.035658,-0.011792,0.020340,-0.009566,0.017773,-0.011544,0.004200,-0.013870,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102094,-0.008398,0.020128,0.000249,-0.006120,-0.008091,0.024116,0.020821,0.041220,-0.017687,0.012903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105080,-0.011471,-0.016307,0.015627,0.021863,0.011891,0.038505,-0.026528,0.000298,-0.014860,-0.008079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101812,-0.014475,-0.017283,-0.001092,0.022463,-0.005212,0.002381,0.016057,-0.005224,0.002921,0.007327,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102797,-0.012335,-0.014539,0.002263,-0.035015,0.005905,-0.003316,-0.034383,0.012083,-0.006389,0.021795,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
103689,-0.014178,-0.016832,0.005638,0.016908,-0.001080,0.003285,-0.000598,-0.011773,0.002617,-0.027317,...,NaN,NaN,NaN,NaN,5.0,NaN,6.0,NaN,NaN,8.0
107486,-0.014045,-0.013105,-0.001334,-0.035849,0.009448,-0.008166,-0.030094,0.013680,-0.016503,-0.001197,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,7.0,NaN,NaN